version: "3"
services:
  mainsite:
    image: steeltoe.azurecr.io/mainsite
    ports:
    - "9081:80"
    environment:
      DOTNET_ENVIRONMENT: Docker
  documentation:
    build: .
    ports:
    - "9082:80"
    environment:
      DOC_ENVIRONMENT: Docker
