version: "3"
services:
  main-site:
    image: steeltoe.azurecr.io/main-site
    ports:
    - "9081:80"
    environment:
      DOTNET_ENVIRONMENT: Docker
  documentation:
    build: .
    ports:
    - "9082:80"
    environment:
      DOC_ENVIRONMENT: Docker
