trigger:
  branches:
    include:
    - main
  paths:
    include:
    - docfx/

variables:
- name: major
  value: 2
- name: minor
  value: 57
- name: patch
  value: 2

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
- stage: Deploy
  displayName: Deploy
  condition:
    not(eq(variables['build.reason'], 'PullRequest'))
  jobs:
  - job: push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo v$(major).$(minor).$(patch) > docfx/version
      displayName: Set Version
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        Dockerfile: docfx/Dockerfile
        containerRegistry: SteeltoeContainerRegistry
        repository: docfx
        tags: |
          $(Build.BuildNumber)
          latest
