name: build-base-layer
on:
### TEMPORARY
  pull_request:
    branches:
    - main
### TEMPORARY

#  push:
#    branches:
#    - main
#    paths:
#    - docfx/

env:
  docfxVersion: 2.57.2
jobs:
  build-push:
    name: Build and push base layer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set DocFX version to use
      run: echo v${{ env.docfxVersion }} > docfx/version
      shell: bash

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: "${{ vars.DOCKER_REGISTRY }}"
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build image
      run: docker build docfx --file "docfx/Dockerfile" -t ${{ vars.DOCKER_REGISTRY }}/docfx:${{ env.docfxVersion }}-${{ github.run_number }} -t ${{ vars.DOCKER_REGISTRY }}/docfx:ghlatest

    - name: Push image
      run: docker push ${{ vars.DOCKER_REGISTRY }}/docfx:${{ env.docfxVersion }}-${{ github.run_number }}
