# name: build-base-layer
# on:
#   push:
#     branches:
#     - main
#     paths:
#     - .github/workflows/build-site.yml
#     - docfx/

# env:
#   docfxVersion: 2.57.2

# permissions:
#   contents: 'read'

# jobs:
#   build-push:
#     name: Build and push base layer
#     runs-on: ubuntu-latest
#     if: !(github.event_name == 'PullRequest')
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Set DocFX version to use
#       run: echo v${{ env.docfxVersion }} > docfx/version
#       shell: bash

#     - name: Login to container registry
#       uses: docker/login-action@v3
#       with:
#         registry: "${{ vars.DOCKER_REGISTRY }}"
#         username: "${{ secrets.DOCKER_USERNAME }}"
#         password: "${{ secrets.DOCKER_PASSWORD }}"

#     - name: Build image
#       run: docker build docfx --file "docfx/Dockerfile" -t ${{ vars.DOCKER_REGISTRY }}/docfx:${{ env.docfxVersion }} -t ${{ vars.DOCKER_REGISTRY }}/docfx:latest

#     - name: Push image
#       run: docker push ${{ vars.DOCKER_REGISTRY }}/docfx:${{ env.docfxVersion }}
