name: build-api-docs
on:
### TEMPORARY
  workflow_run:
    workflows: [build-base-layer]
    types: [completed]
### TEMPORARY

  # push:
  #   branches:
  #   - main
  #   paths:
  #   - Dockerfile-metadata

env:
  tagv2: 2.5.5
  tagv3: 3.2.6
jobs:
  build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and push API docs layer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Steeltoe versions to use
      run: |-
        echo '2:'${{ env.tagv2 }} > metadata.conf
        echo '3:'${{ env.tagv3 }} >> metadata.conf
        echo "STEELTOE_VERSIONS=${{ env.tagv2 }}-${{ env.tagv3 }}" >> $GITHUB_ENV
      shell: bash

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: "${{ env.DOCKER_REGISTRY }}"
        username: "${{ env.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build image
      run: docker build . --file "Dockerfile-metadata" -t ${{ env.DOCKER_REGISTRY }}/documentation-metadata:${{ env.STEELTOE_VERSIONS }}-${{ github.run_number }} -t ${{ env.DOCKER_REGISTRY }}/documentation-metadata:ghlatest

    - name: Push image
      run: docker push ${{ env.DOCKER_REGISTRY }}/documentation-metadata:${{ env.STEELTOE_VERSIONS }}-${{ github.run_number }}
