name: build-api-docs
on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/build-APIdocs-layer.yml
    - Dockerfile-metadata
    - api-*.json
    - build-metadata.sh

  push:
    branches:
    - main
    paths:
    - .github/workflows/build-APIdocs-layer.yml
    - Dockerfile-metadata
    - /api-*.json
    - build-metadata.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  tagv2: 2.5.5
  tagv3: 3.2.6

permissions:
  contents: 'read'

jobs:
  build-push:
    name: Build and push API docs layer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Steeltoe versions to use
      run: |-
        echo '2:'${{ env.tagv2 }} > metadata.conf
        echo '3:'${{ env.tagv3 }} >> metadata.conf
        echo "STEELTOE_VERSIONS=${{ env.tagv2 }}-${{ env.tagv3 }}" >> $GITHUB_ENV
      shell: bash

    - name: Login to container registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: "${{ vars.DOCKER_REGISTRY }}"
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build image
      run: docker build . --file "Dockerfile-metadata" -t ${{ vars.DOCKER_REGISTRY }}/documentation-metadata:${{ env.STEELTOE_VERSIONS }}

    - name: Push image
      if: ${{ github.event_name != 'pull_request' }}
      run: docker push ${{ vars.DOCKER_REGISTRY }}/documentation-metadata:${{ env.STEELTOE_VERSIONS }}
