name: Build Website
on:
### TEMPORARY
  workflow_run:
    workflows: [build-api-docs]
    types: [completed]
### TEMPORARY

  # pull_request:
  #   branches:
  #   - main
  # push:
  #   branches:
  #   - main
  #   paths:
  #   - "*"
  #   - "!README.md"
  #   - "!docfx/"
  #   - "!build-metadata.sh"
  #   - "!Dockerfile-metadata"
  #   - "!metadata.conf"

jobs:
  build-push:
    name: Build and push documentation image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: "${{ vars.DOCKER_REGISTRY }}"
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build image
      run: docker build . --file "Dockerfile" -t ${{ vars.DOCKER_REGISTRY }}/documentation:${{ github.run_id }} -t ${{ vars.DOCKER_REGISTRY }}/documentation:ghlatest

    - name: Push image
      run: docker push ${{ vars.DOCKER_REGISTRY }}/documentation:${{ github.run_id }}
