name: Check broken links

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/check-links.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-links:
    name: Check links in documentation
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            --verbose
            --no-progress
            --cache
            --max-cache-age 1d
            --accept 100..=103,200..=299,403,429
            --exclude 'localhost'
            --exclude 'fortuneservice'
            --exclude '\.internal'
            --exclude 'consul-register-example'
            --exclude '^docker://'
            --exclude-path '.git'
            --exclude-path 'docs/api'
            --max-concurrency 5
            --max-retries 6
            --retry-wait-time 15
            --timeout 30
            '**/*.md'
          fail: true
          jobSummary: false

      - name: Write link checking results to job summary
        if: ${{ !cancelled() }}
        run: |
          sed -i 's/^# Summary$/# Link checking results/' ./lychee/out.md
          cat ./lychee/out.md >> "$GITHUB_STEP_SUMMARY"

      - name: Comment on PR with link check results
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: broken-links-check
          message-path: ./lychee/out.md
